from formtest import *
from decorator_test import *
from utils_test import *
from session_test import *
from auth_test import *
from rest_test import *
from jinja2_test import *
from appstats_test import *
from ereporter_test import *
from live_settings_test import *
from regressiontests.server_error_tests import *
from regressiontests.badurls_test import *
from cache_test.tests import *
